### ISSUE TITLE
2023 and 2024 Tax Year updates

### ISSUE THREAD

**Issue by infinite-monkeys** [hermantran/taxgraphs#5]
Is updating the underlying data files a manual read/scan process or is there some sort of scraper/parser to assist?

**Comment by alexandergknoll** [comment]
@infinite-monkeys I've opened PR #6 which includes tax data for 2023 and 2024.  So far as I can tell there is no straightforward way to scrape or parse all of this data because it's located accross many different state revenue department websites, etc.

**Comment by hermantran** [comment]
@infinite-monkeys I just merged in and deployed @alexandergknoll's update
